
services:
  database:
    image: mysql:9.0
    volumes:
      - invTracker_api:/var/lib/mysql
    ports:
      - '3300:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: invTracker
      MYSQL_USER: deadline
      MYSQL_PASSWORD: Ex@mple12345

volumes:
  invTracker_api:
